# Concept of Tensor

Tensor in Chinese is 张量, which means a multidimensional array. It can be a high-dimensional extension of scalars. vectors, and matrices.

Scalars can be reffered to as 0-dimensional tensors, vectors can be reffered to as 1-dimensional tensors, matrices can be referred to as 2-dimensional tensors, and RGB images can represent 3-dimensional tensors.

**1. in PyTorch, Tensors are similar to ndarrays in NumPy, while Tensors can be compited using GPUs.**

In [42]:
from __future__ import print_function
import torch

**2. Construct Tensor**

In [43]:
# Construct a tensor directly with the data:
# torch.tensor(data, dtype=None, device=None, requires_grad=False, pin_memory=False)
x = torch.tensor([6.12, 4])
print(x)

tensor([6.1200, 4.0000])


In [44]:
# Construct a matrix without initialization:
x = torch.empty(5,5)
print(x)

tensor([[-3.2283e+06,  1.1407e-42,  1.0000e+00,  1.0000e+00,  1.0000e+00],
        [ 1.0000e+00,  1.0000e+00,  1.0000e+00,  1.0000e+00,  1.0000e+00],
        [ 1.0000e+00,  1.0000e+00,  1.0000e+00,  1.0000e+00,  1.0000e+00],
        [ 1.0000e+00,  1.0000e+00,  1.0000e+00,  1.0000e+00,  1.0000e+00],
        [ 1.0000e+00,  1.0000e+00,  1.0000e+00,  1.0000e+00,  1.0000e+00]])


In [57]:
# Construct a matrix randomly:

# torch.rand() & torch.rand_like() Generate a uniform distribution over the interval [0, 1]
# torch.rand(*size, out=None, dtype=None, layout=torch.strided, device=None, requires_grad=False)
x = torch.rand(5,5)
print(x)

# torch.randint() and torch.randint_like() Generate an integer uniform distribution on the interval [low, high].
# randint(low=0, high, size, *, generator=None, out=None, dtype=None, layout=torch.strided, device=None, requires_grad=False)
x = torch.randint(5,(5,5))
print(x)

tensor([[0.6848, 0.0290, 0.3746, 0.1059, 0.1639],
        [0.8721, 0.2828, 0.2465, 0.9344, 0.5077],
        [0.4920, 0.2633, 0.5014, 0.0907, 0.4204],
        [0.7287, 0.6526, 0.9085, 0.4948, 0.3658],
        [0.6323, 0.3110, 0.0188, 0.9014, 0.9692]])
tensor([[4, 3, 3, 2, 2],
        [1, 2, 3, 2, 1],
        [1, 3, 3, 3, 2],
        [0, 0, 2, 3, 1],
        [4, 1, 1, 1, 1]])


In [46]:
# Construct a matrix that is all 0:
x = torch.zeros(5,5)
print(x)

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])


In [47]:
# Construct a matrix that is all 1:
x = torch.ones(5,5)
print(x)

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])


In [53]:
# Create a tensor based on an existing tensor.
x = x.new_ones(5, 5, dtype=torch.double)   # new_* methods take in sizes   
print(x)
x = torch.zeros_like(x, dtype=torch.float)   # override dtype
print(x)
# result has the same size

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]], dtype=torch.float64)
tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])


In [54]:
# Create 1-dimensional tensors of equal difference
x = torch.arange(2, 10, 2)
print(x)

tensor([2, 4, 6, 8])


In [55]:
#Create an evenly divided 1-dimensional tensor, torch.linspace(start, end, step)
x = torch.linspace(2, 10, 6)
print(x)

tensor([ 2.0000,  3.6000,  5.2000,  6.8000,  8.4000, 10.0000])


**3. Check size**

In [49]:
print(x.size())

torch.Size([5, 5])


**4. Operate (e.g. add)**

In [50]:
#add
y = torch.ones(5,5)
print(torch.add(x, y))

print(y.add_(x))

print(x + y)

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])
tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])
tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])


**5. Change the size: If you want to change the size or shape of a tensor, you can use the  methods ```torch.view ```:**

In [51]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(2, 8) 
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


**6. use .item() to get value (one element tensor)**

In [52]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([2.2246])
2.2245583534240723


## Resources
[pytorch 1.0-cn](https://github.com/fendouai/pytorch1.0-cn/blob/master/README.md)

[pytorch note](https://pytorch.zhangxiann.com/1-ji-ben-gai-nian/1.2-tensor-zhang-liang-jie-shao)